export const photosMedia = [
  {
    src: "Photos/16.jpg",
    thumbnail: "Photos/16.jpg",
    thumbnailWidth: 720,
    thumbnailHeight: 960,
    caption:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/17.jpg",
    thumbnail: "Photos/17.jpg",
    thumbnailWidth: 720,
    thumbnailHeight: 960,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/6.jpg",
    thumbnail: "Photos/6.jpg",
    thumbnailWidth: 1280,
    thumbnailHeight: 960,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/28.jpg",
    thumbnail: "Photos/28.jpg",
    thumbnailWidth: 720,
    thumbnailHeight: 960,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/66.jpg",
    thumbnail: "Photos/66.jpg",
    thumbnailWidth: 720,
    thumbnailHeight: 960,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/284.jpg",
    thumbnail: "Photos/284.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/85.jpg",
    thumbnail: "Photos/85.jpg",
    thumbnailWidth: 1280,
    thumbnailHeight: 587,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/120.jpg",
    thumbnail: "Photos/120.jpg",
    thumbnailWidth: 720,
    thumbnailHeight: 960,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/138.jpg",
    thumbnail: "Photos/138.jpg",
    thumbnailWidth: 720,
    thumbnailHeight: 960,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/146.jpg",
    thumbnail: "Photos/146.jpg",
    thumbnailWidth: 960,
    thumbnailHeight: 720,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/112.jpg",
    thumbnail: "Photos/112.jpg",
    thumbnailWidth: 1,
    thumbnailHeight: 1,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/152.jpg",
    thumbnail: "Photos/152.jpg",
    thumbnailWidth: 720,
    thumbnailHeight: 960,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/154.jpg",
    thumbnail: "Photos/154.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 4,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/155.jpg",
    thumbnail: "Photos/155.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 4,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/228.jpg",
    thumbnail: "Photos/228.jpg",
    thumbnailWidth: 3,
    thumbnailHeight: 4,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/265.jpg",
    thumbnail: "Photos/265.jpg",
    thumbnailWidth: 1511,
    thumbnailHeight: 2015,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/269.jpg",
    thumbnail: "Photos/269.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/270.jpg",
    thumbnail: "Photos/270.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/273.jpg",
    thumbnail: "Photos/273.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },

  {
    src: "Photos/277.jpg",
    thumbnail: "Photos/277.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/279.jpg",
    thumbnail: "Photos/279.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/283.jpg",
    thumbnail: "Photos/283.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/70.jpg",
    thumbnail: "Photos/70.jpg",
    thumbnailWidth: 1,
    thumbnailHeight: 1,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/285.jpg",
    thumbnail: "Photos/285.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
  {
    src: "Photos/78.jpg",
    thumbnail: "Photos/78.jpg",
    thumbnailWidth: 1,
    thumbnailHeight: 1,
    caption: "Caption of image",
    link: "https://www.youtube.com/",
  },
];