export const photosNews = [
  {
    src: "Photos/85.jpg",
    thumbnail: "Photos/85.jpg",
    thumbnailWidth: 1280,
    thumbnailHeight: 587,
    thumbnailCaption: "Times of India",
    link: "https://timesofindia.indiatimes.com/",
  },
  {
    src: "Photos/265.jpg",
    thumbnail: "Photos/265.jpg",
    thumbnailWidth: 1511,
    thumbnailHeight: 2015,
    thumbnailCaption: "Hindustan Times",
    link: "https://timesofindia.indiatimes.com/",
  },

  {
    src: "Photos/269.jpg",
    thumbnail: "Photos/269.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    thumbnailCaption: "Minister",
    link: "https://timesofindia.indiatimes.com/",
  },

  {
    src: "Photos/270.jpg",
    thumbnail: "Photos/270.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },

  {
    src: "Photos/273.jpg",
    thumbnail: "Photos/273.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },

  {
    src: "Photos/277.jpg",
    thumbnail: "Photos/277.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },
  {
    src: "Photos/279.jpg",
    thumbnail: "Photos/279.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },
  {
    src: "Photos/283.jpg",
    thumbnail: "Photos/283.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },
  {
    src: "Photos/70.jpg",
    thumbnail: "Photos/70.jpg",
    thumbnailWidth: 1,
    thumbnailHeight: 1,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },
  {
    src: "Photos/285.jpg",
    thumbnail: "Photos/285.jpg",
    thumbnailWidth: 4,
    thumbnailHeight: 3,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },
  {
    src: "Photos/78.jpg",
    thumbnail: "Photos/78.jpg",
    thumbnailWidth: 1,
    thumbnailHeight: 1,
    thumbnailCaption: "Headline",
    link: "https://timesofindia.indiatimes.com/",
  },
];